plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

loom {
    minecraftProvider.mappings(mappings: loom.layered() {
        officialMojangMappings()
        parchment()
    })
    minecraftProvider.minecraftVersion = "1.21.1"
    forgeshadowedFiles = []
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.layered() {
        officialMojangMappings()
        parchment()
    }
    modImplementation "net.fabricmc:fabric-loader:0.15.3"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.97.0+1.21.1"
    include modImplementation("net.fabricmc.fabric-api:fabric-api:0.97.0+1.21.1")
    compileOnly "net.fabricmc.fabric-api:fabric-api:0.97.0+1.21.1"
    implementation 'org.jetbrains:annotations:24.0.1'
    modImplementation 'com.google.code.gson:gson:2.10.1'
}

processResources {
    inputs.property "modVersion", project.version
    filesMatching('fabric.mod.json') {
        filter { it.contains('{{version}}') ? it.replace('{{version}}', project.version) : it }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.named('build') {
    dependsOn('remapJar')
}

tasks.named('remapJar') {
    archiveClassifier = 'dev'
}

tasks.named('remapSourcesJar') {
    archiveClassifier = 'dev-sources'
}
