package com.minewind;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.component.type.AttributeModifierSlot;
import net.minecraft.component.type.AttributeModifiersComponent;
import net.minecraft.entity.attribute.EntityAttributeModifier;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.item.AxeItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.item.SwordItem;
import net.minecraft.item.ToolMaterial;
import net.minecraft.item.ToolMaterials;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;

import java.util.ArrayList;
import java.util.List;

/** GENERATED by tools/gen_weapons.py - edit the table there, not this file. Stats are rough Morrowind approximations. */
public final class MorrowindWeapons {
    public static final List<Item> ALL = new ArrayList<>();

    static {
        add("steel_dagger", ToolMaterials.IRON, false, 2, -1.5f, -0.5, 210, Rarity.COMMON);
        add("silver_dagger", ToolMaterials.IRON, false, 2, -1.5f, -0.5, 180, Rarity.UNCOMMON);
        add("dwarven_dagger", ToolMaterials.IRON, false, 2, -1.5f, -0.5, 300, Rarity.UNCOMMON);
        add("ebony_dagger", ToolMaterials.DIAMOND, false, 3, -1.5f, -0.5, 450, Rarity.RARE);
        add("glass_dagger", ToolMaterials.DIAMOND, false, 4, -1.5f, -0.5, 375, Rarity.RARE);
        add("daedric_dagger", ToolMaterials.DIAMOND, false, 5, -1.5f, -0.5, 600, Rarity.EPIC);
        add("chitin_shortsword", ToolMaterials.STONE, false, 2, -1.8f, -0.25, 175, Rarity.COMMON);
        add("steel_shortsword", ToolMaterials.IRON, false, 3, -1.8f, -0.25, 350, Rarity.COMMON);
        add("silver_shortsword", ToolMaterials.IRON, false, 3, -1.8f, -0.25, 300, Rarity.UNCOMMON);
        add("dwarven_shortsword", ToolMaterials.IRON, false, 3, -1.8f, -0.25, 500, Rarity.UNCOMMON);
        add("iron_longsword", ToolMaterials.IRON, false, 3, -2.4f, 0.0, 350, Rarity.COMMON);
        add("silver_longsword", ToolMaterials.IRON, false, 4, -2.4f, 0.0, 420, Rarity.UNCOMMON);
        add("ebony_longsword", ToolMaterials.DIAMOND, false, 5, -2.4f, 0.0, 1050, Rarity.RARE);
        add("glass_longsword", ToolMaterials.DIAMOND, false, 6, -2.4f, 0.0, 875, Rarity.RARE);
        add("daedric_longsword", ToolMaterials.DIAMOND, false, 7, -2.4f, 0.0, 1400, Rarity.EPIC);
        add("dwarven_claymore", ToolMaterials.IRON, false, 6, -3.0f, 0.75, 800, Rarity.UNCOMMON);
        add("nordic_claymore", ToolMaterials.IRON, false, 6, -3.0f, 0.75, 720, Rarity.UNCOMMON);
        add("daedric_claymore", ToolMaterials.DIAMOND, false, 9, -3.0f, 0.75, 1600, Rarity.EPIC);
        add("iron_waraxe", ToolMaterials.IRON, true, 4, -3.0f, 0.0, 300, Rarity.COMMON);
        add("steel_waraxe", ToolMaterials.IRON, true, 5, -3.0f, 0.0, 420, Rarity.COMMON);
        add("silver_waraxe", ToolMaterials.IRON, true, 5, -3.0f, 0.0, 360, Rarity.UNCOMMON);
        add("steel_battleaxe", ToolMaterials.IRON, true, 7, -3.2f, 0.5, 560, Rarity.COMMON);
        add("nordic_battleaxe", ToolMaterials.IRON, true, 7, -3.2f, 0.5, 720, Rarity.UNCOMMON);
        add("orcish_battleaxe", ToolMaterials.IRON, true, 9, -3.2f, 0.5, 880, Rarity.UNCOMMON);
        add("iron_mace", ToolMaterials.IRON, false, 3, -2.6f, 0.0, 350, Rarity.COMMON);
        add("silver_mace", ToolMaterials.IRON, false, 4, -2.6f, 0.0, 420, Rarity.UNCOMMON);
        add("iron_warhammer", ToolMaterials.IRON, false, 7, -3.3f, 0.5, 450, Rarity.COMMON);
        add("steel_warhammer", ToolMaterials.IRON, false, 8, -3.3f, 0.5, 630, Rarity.COMMON);
        add("dwarven_warhammer", ToolMaterials.IRON, false, 8, -3.3f, 0.5, 900, Rarity.UNCOMMON);
        add("daedric_warhammer", ToolMaterials.DIAMOND, false, 11, -3.3f, 0.5, 1800, Rarity.EPIC);
        add("wooden_club", ToolMaterials.WOOD, false, 2, -2.4f, 0.0, 150, Rarity.COMMON);
        add("wooden_staff", ToolMaterials.WOOD, false, 1, -2.2f, 1.0, 120, Rarity.COMMON);
        add("chitin_spear", ToolMaterials.STONE, false, 3, -2.6f, 1.0, 210, Rarity.COMMON);
        add("iron_spear", ToolMaterials.IRON, false, 3, -2.6f, 1.0, 300, Rarity.COMMON);
        add("steel_spear", ToolMaterials.IRON, false, 4, -2.6f, 1.0, 420, Rarity.COMMON);
        add("silver_spear", ToolMaterials.IRON, false, 4, -2.6f, 1.0, 360, Rarity.UNCOMMON);
        add("dwarven_spear", ToolMaterials.IRON, false, 4, -2.6f, 1.0, 600, Rarity.UNCOMMON);
        add("ebony_spear", ToolMaterials.DIAMOND, false, 5, -2.6f, 1.0, 900, Rarity.RARE);
        add("daedric_spear", ToolMaterials.DIAMOND, false, 7, -2.6f, 1.0, 1200, Rarity.EPIC);
        add("steel_halberd", ToolMaterials.IRON, false, 7, -3.1f, 1.25, 560, Rarity.COMMON);
        add("daedric_halberd", ToolMaterials.DIAMOND, false, 10, -3.1f, 1.25, 1600, Rarity.EPIC);
    }

    private static void add(String id, ToolMaterial material, boolean axe, int damage, float speed, double reach, int durability, Rarity rarity) {
        AttributeModifiersComponent base = axe
                ? AxeItem.createAttributeModifiers(material, damage, speed)
                : SwordItem.createAttributeModifiers(material, damage, speed);
        AttributeModifiersComponent.Builder builder = AttributeModifiersComponent.builder();
        for (AttributeModifiersComponent.Entry entry : base.modifiers()) {
            builder.add(entry.attribute(), entry.modifier(), entry.slot());
        }
        if (reach != 0.0) {
            builder.add(
                    EntityAttributes.PLAYER_ENTITY_INTERACTION_RANGE,
                    new EntityAttributeModifier(Identifier.of(MinewindMod.MOD_ID, id + "_reach"), reach, EntityAttributeModifier.Operation.ADD_VALUE),
                    AttributeModifierSlot.MAINHAND);
        }
        Item.Settings settings = new Item.Settings().maxDamage(durability).rarity(rarity).attributeModifiers(builder.build());
        Item item = axe ? new AxeItem(material, settings) : new SwordItem(material, settings);
        ALL.add(Registry.register(Registries.ITEM, Identifier.of(MinewindMod.MOD_ID, id), item));
    }

    public static void register() {
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COMBAT).register(entries -> ALL.forEach(entries::add));
    }

    private MorrowindWeapons() {}
}
